docker:
  - image: 'cimg/node:<<parameters.node-version>>'
parameters:
  node-version:
    default: lts
    description: >
      Pick a specific cimg/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
